//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nand2TetrisAssembler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nand2TetrisAssembler.Resources.StaticData", typeof(StaticData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;computations-list&gt;
        ///   &lt;computation operation=&quot;0&quot; code=&quot;42&quot;/&gt;
        ///   &lt;computation operation=&quot;1&quot; code=&quot;63&quot;/&gt;
        ///   &lt;computation operation=&quot;-1&quot; code=&quot;58&quot;/&gt;
        ///   &lt;computation operation=&quot;D&quot; code=&quot;12&quot;/&gt;
        ///   &lt;computation operation=&quot;A&quot; code=&quot;48&quot;/&gt;
        ///   &lt;computation operation=&quot;!D&quot; code=&quot;13&quot;/&gt;
        ///   &lt;computation operation=&quot;!A&quot; code=&quot;49&quot;/&gt;
        ///   &lt;computation operation=&quot;-D&quot; code=&quot;15&quot;/&gt;
        ///   &lt;computation operation=&quot;-A&quot; code=&quot;51&quot;/&gt;
        ///   &lt;computation operation=&quot;D+1&quot; code=&quot;31&quot;/&gt;
        ///   &lt;computati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CComputations {
            get {
                return ResourceManager.GetString("CComputations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;destinations-list&gt;
        ///   &lt;destination operation=&quot;&quot; code=&quot;0&quot; /&gt;
        ///   &lt;destination operation=&quot;M&quot; code=&quot;1&quot; /&gt;
        ///   &lt;destination operation=&quot;D&quot; code=&quot;2&quot; /&gt;
        ///   &lt;destination operation=&quot;MD&quot; code=&quot;3&quot; /&gt;
        ///   &lt;destination operation=&quot;A&quot; code=&quot;4&quot; /&gt;
        ///   &lt;destination operation=&quot;AM&quot; code=&quot;5&quot; /&gt;
        ///   &lt;destination operation=&quot;AD&quot; code=&quot;6&quot; /&gt;
        ///   &lt;destination operation=&quot;AMD&quot; code=&quot;7&quot; /&gt;
        ///&lt;/destinations-list&gt;
        ///.
        /// </summary>
        internal static string CDestinations {
            get {
                return ResourceManager.GetString("CDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;jumps-list&gt;
        ///	&lt;jump operation=&quot;&quot; code=&quot;0&quot; /&gt;
        ///	&lt;jump operation=&quot;JGT&quot; code=&quot;1&quot; /&gt;
        ///	&lt;jump operation=&quot;JEQ&quot; code=&quot;2&quot; /&gt;
        ///	&lt;jump operation=&quot;JGE&quot; code=&quot;3&quot; /&gt;
        ///	&lt;jump operation=&quot;JLT&quot; code=&quot;4&quot; /&gt;
        ///	&lt;jump operation=&quot;JNE&quot; code=&quot;5&quot; /&gt;
        ///	&lt;jump operation=&quot;JLE&quot; code=&quot;6&quot; /&gt;
        ///	&lt;jump operation=&quot;JMP&quot; code=&quot;7&quot; /&gt;
        ///&lt;/jumps-list&gt;.
        /// </summary>
        internal static string CJumps {
            get {
                return ResourceManager.GetString("CJumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;symbols-list&gt;
        ///	&lt;symbol key=&quot;R0&quot; value=&quot;0&quot; /&gt;
        ///	&lt;symbol key=&quot;R1&quot; value=&quot;1&quot; /&gt;
        ///	&lt;symbol key=&quot;R2&quot; value=&quot;2&quot; /&gt;
        ///&lt;/symbols-list&gt;.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
    }
}
